/**
 * DataForge V2 — Unsloth 2026.6 exporter.
 *
 * Emits TRL-taxonomy JSONL (Unsloth wraps the TRL trainers) plus a notebook
 * style `train.py`: `FastLanguageModel.from_pretrained(..., load_in_4bit=True)`,
 * `get_peft_model` LoRA, chat-template application and the trainer matching
 * the dataset type (SFTTrainer, DPOTrainer for preference, KTOTrainer /
 * GRPOTrainer for KTO / RL).
 *
 * Runtime-environment agnostic: no DOM, no React.
 */

import type { Example } from '@/engine/types';
import type { RenderContext, SplitFileMap } from './jsonl';
import { buildTrlRows } from './trl';
import { LORA_TARGET_MODULES } from './axolotl';

/** Placeholder used when no target model was selected. */
const MODEL_PLACEHOLDER = 'REPLACE_WITH_BASE_MODEL';

/**
 * Dataset rows for Unsloth — identical to the TRL 1.5 column taxonomy
 * (Unsloth's trainers are TRL trainers under the hood).
 */
export function buildUnslothRows(
  examples: Example[],
  ctx: RenderContext,
): Record<string, unknown>[] {
  return buildTrlRows(examples, ctx);
}

/** Python list literal of the LoRA target modules. */
function pyTargetModules(): string {
  return `[${LORA_TARGET_MODULES.map((m) => `"${m}"`).join(', ')}]`;
}

/** Trainer-specific sections of the Unsloth script. */
function trainerSection(ctx: RenderContext): { imports: string; body: string } {
  const configArgs = [
    'per_device_train_batch_size=2',
    'gradient_accumulation_steps=4',
    'num_train_epochs=3',
    'learning_rate=2e-4',
    'lr_scheduler_type="cosine"',
    'warmup_ratio=0.1',
    'logging_steps=10',
    'optim="adamw_8bit"',
    'output_dir="./outputs"',
  ];
  const argLines = (extra: string[]): string =>
    [...extra, ...configArgs].map((a) => `        ${a},`).join('\n');

  switch (ctx.options.datasetType) {
    case 'sft':
      return {
        imports: 'from trl import SFTConfig, SFTTrainer',
        body: `
def to_text(example):
    return {"text": tokenizer.apply_chat_template(example["messages"], tokenize=False)}


dataset = dataset.map(to_text)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
${argLines(['dataset_text_field="text"', 'max_length=MAX_SEQ_LENGTH'])}
    ),
)`,
      };
    case 'preference':
      return {
        imports: 'from trl import DPOConfig, DPOTrainer',
        body: `
trainer = DPOTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=DPOConfig(
${argLines(['max_length=MAX_SEQ_LENGTH', 'beta=0.1'])}
    ),
)`,
      };
    case 'kto':
      return {
        imports:
          '# KTOTrainer ships from trl.experimental.kto as of TRL 1.5.\nfrom trl.experimental.kto import KTOConfig, KTOTrainer',
        body: `
trainer = KTOTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=KTOConfig(
${argLines(['max_length=MAX_SEQ_LENGTH', 'beta=0.1'])}
    ),
)`,
      };
    case 'rl':
      return {
        imports: 'from trl import GRPOConfig, GRPOTrainer',
        body: `
def reward_exact_answer(completions, answer, **kwargs):
    """Verifiable reward: 1.0 when the completion contains the expected answer."""
    rewards = []
    for completion, expected in zip(completions, answer):
        text = completion[-1]["content"] if isinstance(completion, list) else str(completion)
        rewards.append(1.0 if expected and expected in text else 0.0)
    return rewards


trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    reward_funcs=[reward_exact_answer],
    train_dataset=dataset,
    args=GRPOConfig(
${argLines(['max_completion_length=MAX_SEQ_LENGTH'])}
    ),
)`,
      };
  }
}

/**
 * Build the Unsloth `train.py`: 4-bit base load at the model's recommended
 * sequence length, LoRA adapters over attention+MLP projections, then the
 * dataset-type-matched TRL trainer.
 */
export function buildUnslothScript(ctx: RenderContext, dataFiles: SplitFileMap): string {
  const { model } = ctx;
  const modelId = model?.hfId ?? MODEL_PLACEHOLDER;
  const maxSeqLen = model?.recommendedSeqLen ?? 4096;
  const trainFile = dataFiles.train ?? 'data/train.jsonl';
  const section = trainerSection(ctx);

  return `"""Fine-tune ${modelId} with Unsloth 2026.6 — generated by DataForge Studio.

Install:
    pip install "unsloth==2026.6.*"

Run:
    python train.py
"""

from unsloth import FastLanguageModel
from datasets import load_dataset
${section.imports}

MAX_SEQ_LENGTH = ${maxSeqLen}

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="${modelId}",
    max_seq_length=MAX_SEQ_LENGTH,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=32,
    lora_alpha=64,
    lora_dropout=0.05,
    target_modules=${pyTargetModules()},
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

dataset = load_dataset("json", data_files="${trainFile}", split="train")
${section.body}
trainer.train()
model.save_pretrained("./outputs/final")
tokenizer.save_pretrained("./outputs/final")
`;
}
